### ISSUE TITLE
Enabling Utterances comments

### ISSUE THREAD

**Issue by tarquin-the-brave** [funkydan2/hugo-kiera#36]
Hi,

I'm having a little trouble enabling commenting with utterances.

I've followed the [utterances docs](https://utteranc.es/) and installed the utterance app on github, enabling it for my blog repo. Although I couldn't find the "Blog Post ↔️ Issue Mapping" config anywhere on Github.

I've copied the two fields from the example config in the Keira theme into my hugo config:

```toml
[params]                                                                                                                                              
    utterancesRepo = "https://github.com/tarquin-the-brave/blog"                                                                                      
    utterancesIssueTerm = "pathname" 
```

I didn't know what to put for `utteranceIssueTerm` so I just left as it is.

I've rebuilt with `hugo` and committed and pushed the changes under the `docs/` directory.  And commenting hasn't appeared on any blog posts.

Is there something I'm missing?  What am I supposed to set `utterancesIssueTerm` to?

Thanks!
